#!/bin/bash

mkdir -p ~/Library/Application\ Support/TextMate/Bundles
cd ~/Library/Application\ Support/TextMate/Bundles
git clone git://github.com/drnic/ruby-on-rails-tmbundle.git "Ruby on Rails.tmbundle"
git clone git://github.com/drnic/ruby-tmbundle.git "Ruby.tmbundle"
git clone git://github.com/rspec/rspec-tmbundle.git "RSpec.tmbundle"
git clone git://github.com/kswedberg/jquery-tmbundle.git "JavaScript jQuery.tmbundle"
git clone git://github.com/metavida/apidock-tmbundle.git "APIdock.tmbundle"
git clone git://github.com/aslakhellesoy/cucumber-tmbundle.git Cucumber.tmbundle
git clone git://github.com/timcharper/rubyamp.git RubyAMP.tmbundle
git clone git://github.com/drnic/Bundler.tmbundle.git
git clone git://github.com/aussiegeek/ruby-sass-tmbundle.git 'RubySass.tmbundle'
osascript -e 'tell app "TextMate" to reload bundles'