#!/bin/bash
echo '
------------------------------------------------------------------------------
Install homebrew with:
 ruby -e "$(curl -fsS http://gist.github.com/raw/323731/install_homebrew.rb)"

Then install mongodb:
 brew install mongo

More info on http://github.com/mxcl/homebrew
------------------------------------------------------------------------------
'
