source ~/.bash/aliases
source ~/.bash/completions
source ~/.bash/paths
source ~/.bash/config
source ~/.git-prompt.sh

if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi

[[ -r $rvm_path/scripts/completion ]] && source $rvm_path/scripts/completion

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

if [ -f ~/.localrc ]; then
  . ~/.localrc
fi
export PATH="/usr/local/opt/elasticsearch@2.4/bin:$PATH"
