call pathogen#runtime_prepend_subdirectories(expand('~/.vim/bundles'))

set tabstop=2
set smarttab
set shiftwidth=2
set autoindent
set expandtab

set background=light
colorscheme solarized
set guifont=Monaco:h14

" Explicitly set 256 color support
set t_Co=256

" Enable filetype-specific indenting and plugins
filetype plugin indent on

" Syntax Highlighting on
set nocompatible
syntax on

" Disable bell.
set vb t_vb=

" resize current buffer in the given direction
nnoremap <D-right> :vertical resize +5<cr>
nnoremap <D-up> :resize -5<cr>
nnoremap <D-down> :resize +5<cr>
nnoremap <D-left> :vertical resize -5<cr>

" dispatch.vim keybinding
nnoremap <F9> :Dispatch<CR>

" line numbers
set number
set numberwidth=3

" Open new horizontal split windows below current
set splitbelow

" Open new vertical split windows to the right
set splitright

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$

" don't wrap lines that are too long
set nowrap

autocmd BufWritePre * :%s/\s\+$//e
autocmd BufRead *.json :set ft=javascript
autocmd BufRead *.jbuilder :set ft=ruby
autocmd BufRead *.serenade :set ft=slim

autocmd BufRead,BufNewFile *.py set shiftwidth=4
autocmd BufRead,BufNewFile *.py set tabstop=4

" leader is set to the dash key, as it is much friendlier on a swedish
" keyboard
let mapleader = "-"

" don't ever create swap files, they're annoying!
set nobackup
set noswapfile

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" highlight search results
set hlsearch
set incsearch

" clear highlighted matches with space
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" allow switching away from buffers that have changes
set nohidden

let g:ctrlp_cmd = 'CtrlPMRU'

syntax enable
let g:solarized_termcolors=256
colorscheme solarized
set background=dark
