call pathogen#runtime_prepend_subdirectories(expand('~/.vim/bundles'))

set tabstop=2
set smarttab
set shiftwidth=2
set autoindent
set expandtab
set guifont=Monaco:h20

" Explicitly set 256 color support
set t_Co=256

" Enable filetype-specific indenting and plugins
filetype plugin indent on

" Syntax Highlighting on
set nocompatible
syntax on

" Disable bell.
set vb t_vb=

" line numbers
set number
set numberwidth=3

" Open new horizontal split windows below current
set splitbelow

" Open new vertical split windows to the right
set splitright

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$

" don't wrap lines that are too long
set nowrap

autocmd BufWritePre * :%s/\s\+$//e
autocmd BufRead *.json :set ft=javascript

" leader is set to the dash key, as it is much friendlier on a swedish
" keyboard
let mapleader = "-"
autocmd BufRead *.serenade :set ft=slim

" don't ever create swap files, they're annoying!
set nobackup
set noswapfile

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" highlight search results
set hlsearch
set incsearch

" clear highlighted matches with space
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" remap enter/shift-enter to insert blank lines
map <S-Enter> O<Esc>
map <CR> o<Esc>

" allow switching away from buffers that have changes
set hidden
